/**
 * ============================================
 *  Database Seed Script — Indian Singers Edition
 * ============================================
 * 
 * Populates the MongoDB database with 120+ Indian singer songs
 * across all supported moods for testing and demo purposes.
 * 
 * Features famous Indian artists like:
 * Arijit Singh, Shreya Ghoshal, A.R. Rahman, Lata Mangeshkar,
 * Kishore Kumar, Atif Aslam, Neha Kakkar, Badshah, and many more.
 * 
 * Usage: npm run seed
 */

const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');

// Load environment variables
dotenv.config({ path: path.join(__dirname, '../../.env') });

const Song = require('../models/Song');

// =============================================
//  INDIAN SINGERS SONG DATABASE — 126 Songs
// =============================================

const dummySongs = [

  // ════════════════════════════════════════════
  //  😢 SAD SONGS (14 songs)
  // ════════════════════════════════════════════
  {
    title: 'Tujhe Bhula Diya',
    artist: 'Mohit Chauhan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sad', 'Heartbreak'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1518458028785-8f5b2a7a2a84?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    audioFeatures: { energy: 0.25, valence: 0.15, danceability: 0.2, tempo: 75, acousticness: 0.7, instrumentalness: 0 },
    popularity: 90,
  },
  {
    title: 'Channa Mereya',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sad', 'Emotional'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    audioFeatures: { energy: 0.3, valence: 0.12, danceability: 0.2, tempo: 78, acousticness: 0.75, instrumentalness: 0 },
    popularity: 98,
  },
  {
    title: 'Agar Tum Saath Ho',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sad', 'Romantic'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1446057032654-9d8885f0e7d7?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    audioFeatures: { energy: 0.28, valence: 0.18, danceability: 0.22, tempo: 72, acousticness: 0.8, instrumentalness: 0 },
    popularity: 96,
  },
  {
    title: 'Phir Bhi Tumko Chaahunga',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sad', 'Longing'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    audioFeatures: { energy: 0.22, valence: 0.1, danceability: 0.18, tempo: 70, acousticness: 0.82, instrumentalness: 0 },
    popularity: 94,
  },
  {
    title: 'Tujhko Jo Paaya',
    artist: 'Mohit Chauhan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sad', 'Emotional'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
    audioFeatures: { energy: 0.2, valence: 0.15, danceability: 0.15, tempo: 68, acousticness: 0.85, instrumentalness: 0 },
    popularity: 82,
  },
  {
    title: 'Judaai',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sad', 'Heartbreak'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
    audioFeatures: { energy: 0.18, valence: 0.08, danceability: 0.12, tempo: 65, acousticness: 0.88, instrumentalness: 0 },
    popularity: 85,
  },
  {
    title: 'Tere Bina',
    artist: 'A.R. Rahman',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sad', 'Soulful'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1499346030926-9a72daac6c63?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    audioFeatures: { energy: 0.25, valence: 0.2, danceability: 0.2, tempo: 75, acousticness: 0.78, instrumentalness: 0 },
    popularity: 91,
  },
  {
    title: 'Lag Ja Gale',
    artist: 'Lata Mangeshkar',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Classic', 'Sad'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1428908728789-d2de25dbd4e2?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    audioFeatures: { energy: 0.15, valence: 0.22, danceability: 0.15, tempo: 62, acousticness: 0.92, instrumentalness: 0 },
    popularity: 95,
  },
  {
    title: 'Mann Bharrya',
    artist: 'B Praak',
    genre: 'Punjabi',
    genres: ['Punjabi', 'Sad', 'Heartbreak'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    audioFeatures: { energy: 0.3, valence: 0.15, danceability: 0.2, tempo: 80, acousticness: 0.65, instrumentalness: 0 },
    popularity: 92,
  },
  {
    title: 'Tera Ban Jaunga',
    artist: 'Akhil Sachdeva',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sad', 'Romantic'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1500964757637-c85e8a162699?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    audioFeatures: { energy: 0.28, valence: 0.2, danceability: 0.22, tempo: 76, acousticness: 0.7, instrumentalness: 0 },
    popularity: 88,
  },
  {
    title: 'Teri Mitti',
    artist: 'B Praak',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Patriotic', 'Emotional'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
    audioFeatures: { energy: 0.35, valence: 0.12, danceability: 0.15, tempo: 82, acousticness: 0.72, instrumentalness: 0 },
    popularity: 93,
  },
  {
    title: 'Dil Diyan Gallan',
    artist: 'Atif Aslam',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sad', 'Romantic'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
    audioFeatures: { energy: 0.3, valence: 0.25, danceability: 0.25, tempo: 78, acousticness: 0.68, instrumentalness: 0 },
    popularity: 91,
  },
  {
    title: 'Kabira',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sufi', 'Sad'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    audioFeatures: { energy: 0.32, valence: 0.2, danceability: 0.25, tempo: 80, acousticness: 0.6, instrumentalness: 0 },
    popularity: 89,
  },
  {
    title: 'Tum Hi Ho',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sad', 'Love'],
    mood: 'sad',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    audioFeatures: { energy: 0.35, valence: 0.18, danceability: 0.2, tempo: 78, acousticness: 0.7, instrumentalness: 0 },
    popularity: 99,
  },

  // ════════════════════════════════════════════
  //  💕 ROMANTIC SONGS (14 songs)
  // ════════════════════════════════════════════
  {
    title: 'Raabta',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Romantic', 'Soulful'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    audioFeatures: { energy: 0.4, valence: 0.65, danceability: 0.4, tempo: 90, acousticness: 0.6, instrumentalness: 0 },
    popularity: 92,
  },
  {
    title: 'Tere Liye',
    artist: 'Atif Aslam',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Romantic', 'Love'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1431440869543-efaf3388c585?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    audioFeatures: { energy: 0.38, valence: 0.7, danceability: 0.35, tempo: 88, acousticness: 0.65, instrumentalness: 0 },
    popularity: 89,
  },
  {
    title: 'Pehla Nasha',
    artist: 'Udit Narayan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Classic', 'Romantic'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
    audioFeatures: { energy: 0.35, valence: 0.75, danceability: 0.45, tempo: 95, acousticness: 0.55, instrumentalness: 0 },
    popularity: 96,
  },
  {
    title: 'Tujh Mein Rab Dikhta Hai',
    artist: 'Roop Kumar Rathod',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Romantic', 'Devotional'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
    audioFeatures: { energy: 0.3, valence: 0.72, danceability: 0.3, tempo: 85, acousticness: 0.7, instrumentalness: 0 },
    popularity: 94,
  },
  {
    title: 'Kal Ho Naa Ho',
    artist: 'Sonu Nigam',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Romantic', 'Emotional'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
    audioFeatures: { energy: 0.42, valence: 0.68, danceability: 0.4, tempo: 92, acousticness: 0.5, instrumentalness: 0 },
    popularity: 97,
  },
  {
    title: 'Tum Se Hi',
    artist: 'Mohit Chauhan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Romantic', 'Feel-Good'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
    audioFeatures: { energy: 0.38, valence: 0.72, danceability: 0.42, tempo: 95, acousticness: 0.55, instrumentalness: 0 },
    popularity: 93,
  },
  {
    title: 'Janam Janam',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Romantic', 'Wedding'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.4, valence: 0.7, danceability: 0.35, tempo: 88, acousticness: 0.6, instrumentalness: 0 },
    popularity: 95,
  },
  {
    title: 'Tera Hone Laga Hoon',
    artist: 'Atif Aslam',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Romantic', 'Love'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.42, valence: 0.75, danceability: 0.45, tempo: 98, acousticness: 0.5, instrumentalness: 0 },
    popularity: 90,
  },
  {
    title: 'Mere Haath Mein',
    artist: 'Sonu Nigam',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Romantic', 'Classic'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    audioFeatures: { energy: 0.35, valence: 0.68, danceability: 0.38, tempo: 90, acousticness: 0.58, instrumentalness: 0 },
    popularity: 86,
  },
  {
    title: 'Bolna',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Romantic', 'Soulful'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    audioFeatures: { energy: 0.38, valence: 0.65, danceability: 0.4, tempo: 88, acousticness: 0.6, instrumentalness: 0 },
    popularity: 91,
  },
  {
    title: 'Suraj Hua Maddham',
    artist: 'Alka Yagnik',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Classic', 'Romantic'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
    audioFeatures: { energy: 0.3, valence: 0.7, danceability: 0.35, tempo: 85, acousticness: 0.65, instrumentalness: 0 },
    popularity: 94,
  },
  {
    title: 'Mann Mera',
    artist: 'Sherya Ghoshal',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Romantic', 'Sweet'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1518458028785-8f5b2a7a2a84?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
    audioFeatures: { energy: 0.35, valence: 0.72, danceability: 0.38, tempo: 90, acousticness: 0.6, instrumentalness: 0 },
    popularity: 87,
  },
  {
    title: 'Hawayein',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Romantic', 'Breezy'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1528722828814-77b9b83aafb2?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
    audioFeatures: { energy: 0.35, valence: 0.7, danceability: 0.4, tempo: 92, acousticness: 0.55, instrumentalness: 0 },
    popularity: 93,
  },
  {
    title: 'Khairiyat',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Romantic', 'Emotional'],
    mood: 'romantic',
    image: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
    audioFeatures: { energy: 0.32, valence: 0.65, danceability: 0.35, tempo: 85, acousticness: 0.68, instrumentalness: 0 },
    popularity: 96,
  },

  // ════════════════════════════════════════════
  //  😊 HAPPY SONGS (14 songs)
  // ════════════════════════════════════════════
  {
    title: 'Gallan Goodiyan',
    artist: 'Shankar Mahadevan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Happy', 'Dance'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    audioFeatures: { energy: 0.8, valence: 0.9, danceability: 0.75, tempo: 120, acousticness: 0.2, instrumentalness: 0 },
    popularity: 93,
  },
  {
    title: 'Balam Pichkari',
    artist: 'Vishal-Shekhar',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Happy', 'Festival'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    audioFeatures: { energy: 0.85, valence: 0.92, danceability: 0.85, tempo: 130, acousticness: 0.1, instrumentalness: 0 },
    popularity: 95,
  },
  {
    title: 'London Thumakda',
    artist: 'Labh Janjua',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Happy', 'Wedding'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    audioFeatures: { energy: 0.82, valence: 0.88, danceability: 0.8, tempo: 128, acousticness: 0.15, instrumentalness: 0 },
    popularity: 91,
  },
  {
    title: 'Badtameez Dil',
    artist: 'Benny Dayal',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Happy', 'Party'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    audioFeatures: { energy: 0.88, valence: 0.85, danceability: 0.82, tempo: 132, acousticness: 0.08, instrumentalness: 0 },
    popularity: 94,
  },
  {
    title: 'Ainvayi Ainvayi',
    artist: 'Salim Merchant',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Happy', 'Fun'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    audioFeatures: { energy: 0.78, valence: 0.85, danceability: 0.72, tempo: 125, acousticness: 0.2, instrumentalness: 0 },
    popularity: 87,
  },
  {
    title: 'Dil Dhadakne Do',
    artist: 'Priyanka Chopra',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Happy', 'Feel-Good'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    audioFeatures: { energy: 0.75, valence: 0.82, danceability: 0.7, tempo: 118, acousticness: 0.25, instrumentalness: 0 },
    popularity: 85,
  },
  {
    title: 'Ude Dil Befikre',
    artist: 'Benny Dayal',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Happy', 'Carefree'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1571266028243-d220c6a8b0e5?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    audioFeatures: { energy: 0.82, valence: 0.88, danceability: 0.78, tempo: 125, acousticness: 0.12, instrumentalness: 0 },
    popularity: 86,
  },
  {
    title: 'Abhi Toh Party Shuru Hui Hai',
    artist: 'Badshah',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Happy', 'Party'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    audioFeatures: { energy: 0.9, valence: 0.85, danceability: 0.88, tempo: 135, acousticness: 0.05, instrumentalness: 0.1 },
    popularity: 90,
  },
  {
    title: 'Ruk Ja O Dil Deewane',
    artist: 'Udit Narayan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Classic', 'Happy'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    audioFeatures: { energy: 0.7, valence: 0.82, danceability: 0.65, tempo: 115, acousticness: 0.35, instrumentalness: 0 },
    popularity: 92,
  },
  {
    title: 'Koi Mil Gaya',
    artist: 'Udit Narayan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Classic', 'Happy'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    audioFeatures: { energy: 0.72, valence: 0.8, danceability: 0.68, tempo: 118, acousticness: 0.3, instrumentalness: 0 },
    popularity: 89,
  },
  {
    title: 'Nagada Sang Dhol',
    artist: 'Shreya Ghoshal',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Happy', 'Dance'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    audioFeatures: { energy: 0.85, valence: 0.88, danceability: 0.82, tempo: 128, acousticness: 0.12, instrumentalness: 0 },
    popularity: 91,
  },
  {
    title: 'Radha',
    artist: 'Shreya Ghoshal',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Happy', 'Festive'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1431440869543-efaf3388c585?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    audioFeatures: { energy: 0.8, valence: 0.85, danceability: 0.78, tempo: 125, acousticness: 0.15, instrumentalness: 0 },
    popularity: 88,
  },
  {
    title: 'Kar Gayi Chull',
    artist: 'Neha Kakkar',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Happy', 'Party'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    audioFeatures: { energy: 0.88, valence: 0.9, danceability: 0.85, tempo: 130, acousticness: 0.08, instrumentalness: 0 },
    popularity: 93,
  },
  {
    title: 'Nachde Ne Saare',
    artist: 'Vishal-Shekhar',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Happy', 'Wedding'],
    mood: 'happy',
    image: 'https://images.unsplash.com/photo-1517430529647-90cce5b4fb15?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    audioFeatures: { energy: 0.82, valence: 0.86, danceability: 0.8, tempo: 126, acousticness: 0.12, instrumentalness: 0 },
    popularity: 86,
  },

  // ════════════════════════════════════════════
  //  🔥 ENERGETIC SONGS (14 songs)
  // ════════════════════════════════════════════
  {
    title: 'Khalibali',
    artist: 'Shivam Pathak',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Intense'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1571266028243-d220c6a8b0e5?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    audioFeatures: { energy: 0.95, valence: 0.72, danceability: 0.8, tempo: 140, acousticness: 0.05, instrumentalness: 0.1 },
    popularity: 88,
  },
  {
    title: 'Tattad Tattad',
    artist: 'Aditya Narayan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Dance'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    audioFeatures: { energy: 0.92, valence: 0.78, danceability: 0.85, tempo: 145, acousticness: 0.08, instrumentalness: 0 },
    popularity: 85,
  },
  {
    title: 'Malhari',
    artist: 'Vishal Dadlani',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Victory'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    audioFeatures: { energy: 0.95, valence: 0.8, danceability: 0.82, tempo: 150, acousticness: 0.05, instrumentalness: 0.05 },
    popularity: 92,
  },
  {
    title: 'Zinda',
    artist: 'Shankar Mahadevan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Motivational'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    audioFeatures: { energy: 0.9, valence: 0.75, danceability: 0.7, tempo: 138, acousticness: 0.1, instrumentalness: 0 },
    popularity: 87,
  },
  {
    title: 'Chak De India',
    artist: 'Sukhwinder Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Patriotic'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1517430529647-90cce5b4fb15?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    audioFeatures: { energy: 0.92, valence: 0.82, danceability: 0.75, tempo: 142, acousticness: 0.08, instrumentalness: 0 },
    popularity: 96,
  },
  {
    title: 'Sultan',
    artist: 'Sukhwinder Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Powerful'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    audioFeatures: { energy: 0.88, valence: 0.7, danceability: 0.7, tempo: 135, acousticness: 0.1, instrumentalness: 0 },
    popularity: 89,
  },
  {
    title: 'Dhoom Machale',
    artist: 'Sunidhi Chauhan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Action'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    audioFeatures: { energy: 0.9, valence: 0.78, danceability: 0.82, tempo: 140, acousticness: 0.05, instrumentalness: 0.1 },
    popularity: 94,
  },
  {
    title: 'Dangal',
    artist: 'Daler Mehndi',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Sports'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    audioFeatures: { energy: 0.88, valence: 0.75, danceability: 0.78, tempo: 135, acousticness: 0.1, instrumentalness: 0 },
    popularity: 91,
  },
  {
    title: 'Bhaag Milkha Bhaag',
    artist: 'Shankar Mahadevan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Motivational'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    audioFeatures: { energy: 0.92, valence: 0.72, danceability: 0.72, tempo: 145, acousticness: 0.08, instrumentalness: 0 },
    popularity: 90,
  },
  {
    title: 'Deva Shree Ganesha',
    artist: 'Ajay-Atul',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Devotional'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    audioFeatures: { energy: 0.93, valence: 0.8, danceability: 0.78, tempo: 148, acousticness: 0.12, instrumentalness: 0 },
    popularity: 88,
  },
  {
    title: 'Suno Gaur Se Duniya Walon',
    artist: 'Shankar Mahadevan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Patriotic'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    audioFeatures: { energy: 0.88, valence: 0.76, danceability: 0.7, tempo: 140, acousticness: 0.1, instrumentalness: 0 },
    popularity: 86,
  },
  {
    title: 'Kar Har Maidan Fateh',
    artist: 'Sukhwinder Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Victory'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    audioFeatures: { energy: 0.9, valence: 0.7, danceability: 0.68, tempo: 138, acousticness: 0.08, instrumentalness: 0 },
    popularity: 87,
  },
  {
    title: 'Brothers Anthem',
    artist: 'Vishal Dadlani',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Sports'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1518458028785-8f5b2a7a2a84?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    audioFeatures: { energy: 0.91, valence: 0.72, danceability: 0.75, tempo: 142, acousticness: 0.06, instrumentalness: 0.1 },
    popularity: 83,
  },
  {
    title: 'Jai Ho',
    artist: 'A.R. Rahman',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Energetic', 'Celebration'],
    mood: 'energetic',
    image: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    audioFeatures: { energy: 0.88, valence: 0.85, danceability: 0.82, tempo: 135, acousticness: 0.1, instrumentalness: 0 },
    popularity: 98,
  },

  // ════════════════════════════════════════════
  //  🧘 CALM SONGS (14 songs)
  // ════════════════════════════════════════════
  {
    title: 'Kun Faya Kun',
    artist: 'A.R. Rahman',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sufi', 'Spiritual'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
    audioFeatures: { energy: 0.2, valence: 0.6, danceability: 0.15, tempo: 68, acousticness: 0.85, instrumentalness: 0.2 },
    popularity: 97,
  },
  {
    title: 'Tere Bina',
    artist: 'A.R. Rahman',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Calm', 'Soulful'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1528722828814-77b9b83aafb2?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
    audioFeatures: { energy: 0.18, valence: 0.55, danceability: 0.15, tempo: 65, acousticness: 0.88, instrumentalness: 0 },
    popularity: 90,
  },
  {
    title: 'Iktara',
    artist: 'Amit Trivedi',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Calm', 'Folk'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.2, valence: 0.58, danceability: 0.2, tempo: 72, acousticness: 0.82, instrumentalness: 0 },
    popularity: 88,
  },
  {
    title: 'Ae Dil Hai Mushkil',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Calm', 'Emotional'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.25, valence: 0.5, danceability: 0.2, tempo: 75, acousticness: 0.75, instrumentalness: 0 },
    popularity: 94,
  },
  {
    title: 'Maeri',
    artist: 'Euphoria',
    genre: 'Indie',
    genres: ['Indie', 'Calm', 'Rock Ballad'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
    audioFeatures: { energy: 0.22, valence: 0.52, danceability: 0.2, tempo: 70, acousticness: 0.78, instrumentalness: 0 },
    popularity: 85,
  },
  {
    title: 'Aahatein',
    artist: 'Agnee',
    genre: 'Indie',
    genres: ['Indie', 'Calm', 'Alternative'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
    audioFeatures: { energy: 0.18, valence: 0.5, danceability: 0.15, tempo: 68, acousticness: 0.8, instrumentalness: 0.1 },
    popularity: 80,
  },
  {
    title: 'Piya Haji Ali',
    artist: 'A.R. Rahman',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Sufi', 'Calm'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.15, valence: 0.55, danceability: 0.12, tempo: 62, acousticness: 0.9, instrumentalness: 0.1 },
    popularity: 87,
  },
  {
    title: 'Lukka Chuppi',
    artist: 'A.R. Rahman',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Calm', 'Lullaby'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.12, valence: 0.58, danceability: 0.1, tempo: 60, acousticness: 0.92, instrumentalness: 0.2 },
    popularity: 86,
  },
  {
    title: 'Kabhi Neem Neem',
    artist: 'Shreya Ghoshal',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Calm', 'Sweet'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1446057032654-9d8885f0e7d7?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
    audioFeatures: { energy: 0.2, valence: 0.6, danceability: 0.18, tempo: 70, acousticness: 0.82, instrumentalness: 0 },
    popularity: 82,
  },
  {
    title: 'Yeh Honsla',
    artist: 'Salim Merchant',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Calm', 'Motivational'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1500964757637-c85e8a162699?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
    audioFeatures: { energy: 0.25, valence: 0.55, danceability: 0.2, tempo: 72, acousticness: 0.75, instrumentalness: 0 },
    popularity: 83,
  },
  {
    title: 'Tu Jhoom',
    artist: 'Abida Parveen',
    genre: 'Sufi',
    genres: ['Sufi', 'Calm', 'Qawwali'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.22, valence: 0.52, danceability: 0.18, tempo: 68, acousticness: 0.85, instrumentalness: 0 },
    popularity: 84,
  },
  {
    title: 'Jashn-e-Bahara',
    artist: 'Javed Ali',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Calm', 'Romantic'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1431440869543-efaf3388c585?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.2, valence: 0.6, danceability: 0.15, tempo: 65, acousticness: 0.85, instrumentalness: 0 },
    popularity: 89,
  },
  {
    title: 'Naina',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Calm', 'Soulful'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
    audioFeatures: { energy: 0.2, valence: 0.55, danceability: 0.18, tempo: 70, acousticness: 0.8, instrumentalness: 0 },
    popularity: 88,
  },
  {
    title: 'Mitwa',
    artist: 'Shafqat Amanat Ali',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Calm', 'Emotional'],
    mood: 'calm',
    image: 'https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
    audioFeatures: { energy: 0.22, valence: 0.58, danceability: 0.2, tempo: 72, acousticness: 0.78, instrumentalness: 0 },
    popularity: 85,
  },

  // ════════════════════════════════════════════
  //  🌙 MELANCHOLY SONGS (14 songs)
  // ════════════════════════════════════════════
  {
    title: 'Tujhe Kitna Chahne Lage',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Longing'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1499346030926-9a72daac6c63?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.28, valence: 0.28, danceability: 0.22, tempo: 78, acousticness: 0.72, instrumentalness: 0 },
    popularity: 95,
  },
  {
    title: 'Dil Se Re',
    artist: 'A.R. Rahman',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Intense'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1428908728789-d2de25dbd4e2?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.35, valence: 0.3, danceability: 0.25, tempo: 82, acousticness: 0.6, instrumentalness: 0 },
    popularity: 92,
  },
  {
    title: 'Enna Sona',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Soulful'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.25, valence: 0.3, danceability: 0.22, tempo: 75, acousticness: 0.75, instrumentalness: 0 },
    popularity: 91,
  },
  {
    title: 'Samjhawan',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Pain'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.22, valence: 0.25, danceability: 0.18, tempo: 72, acousticness: 0.78, instrumentalness: 0 },
    popularity: 90,
  },
  {
    title: 'Tadap Tadap',
    artist: 'KK',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Heartbreak'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.35, valence: 0.2, danceability: 0.2, tempo: 80, acousticness: 0.6, instrumentalness: 0 },
    popularity: 88,
  },
  {
    title: 'Aankhon Mein Teri',
    artist: 'KK',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Nostalgic'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1500964757637-c85e8a162699?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.3, valence: 0.28, danceability: 0.22, tempo: 78, acousticness: 0.65, instrumentalness: 0 },
    popularity: 86,
  },
  {
    title: 'Muskurane',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Bittersweet'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1518458028785-8f5b2a7a2a84?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.25, valence: 0.32, danceability: 0.2, tempo: 75, acousticness: 0.72, instrumentalness: 0 },
    popularity: 89,
  },
  {
    title: 'Kuch To Hai',
    artist: 'Armaan Malik',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Emotional'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.28, valence: 0.3, danceability: 0.22, tempo: 76, acousticness: 0.68, instrumentalness: 0 },
    popularity: 84,
  },
  {
    title: 'Bekhayali',
    artist: 'Sachet Tandon',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Intense'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.35, valence: 0.22, danceability: 0.2, tempo: 82, acousticness: 0.6, instrumentalness: 0 },
    popularity: 93,
  },
  {
    title: 'Heeriye',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Love'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.3, valence: 0.3, danceability: 0.25, tempo: 78, acousticness: 0.65, instrumentalness: 0 },
    popularity: 91,
  },
  {
    title: 'Dil Ibaadat',
    artist: 'KK',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Soulful'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1446057032654-9d8885f0e7d7?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.25, valence: 0.28, danceability: 0.18, tempo: 72, acousticness: 0.75, instrumentalness: 0 },
    popularity: 87,
  },
  {
    title: 'Phir Le Aaya Dil',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Rain'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1428908728789-d2de25dbd4e2?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.22, valence: 0.25, danceability: 0.18, tempo: 70, acousticness: 0.8, instrumentalness: 0 },
    popularity: 86,
  },
  {
    title: 'Dooriyan',
    artist: 'Rahat Fateh Ali Khan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Longing'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.28, valence: 0.22, danceability: 0.2, tempo: 75, acousticness: 0.72, instrumentalness: 0 },
    popularity: 85,
  },
  {
    title: 'Laal Ishq',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Melancholy', 'Passionate'],
    mood: 'melancholy',
    image: 'https://images.unsplash.com/photo-1499346030926-9a72daac6c63?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.35, valence: 0.25, danceability: 0.2, tempo: 82, acousticness: 0.6, instrumentalness: 0 },
    popularity: 90,
  },

  // ════════════════════════════════════════════
  //  🎯 FOCUS SONGS (14 songs)
  // ════════════════════════════════════════════
  {
    title: 'Gurus of Peace',
    artist: 'A.R. Rahman',
    genre: 'Fusion',
    genres: ['Fusion', 'Focus', 'Instrumental'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    audioFeatures: { energy: 0.35, valence: 0.5, danceability: 0.25, tempo: 85, acousticness: 0.55, instrumentalness: 0.4 },
    popularity: 82,
  },
  {
    title: 'Maa Tujhe Salaam',
    artist: 'A.R. Rahman',
    genre: 'Indian Classical',
    genres: ['Indian Classical', 'Focus', 'Patriotic'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    audioFeatures: { energy: 0.38, valence: 0.52, danceability: 0.2, tempo: 82, acousticness: 0.6, instrumentalness: 0.3 },
    popularity: 90,
  },
  {
    title: 'Bombay Theme',
    artist: 'A.R. Rahman',
    genre: 'Indian Classical',
    genres: ['Indian Classical', 'Focus', 'Instrumental'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    audioFeatures: { energy: 0.3, valence: 0.5, danceability: 0.15, tempo: 78, acousticness: 0.7, instrumentalness: 0.8 },
    popularity: 88,
  },
  {
    title: 'Theme of Lagaan',
    artist: 'A.R. Rahman',
    genre: 'Indian Classical',
    genres: ['Indian Classical', 'Focus', 'Cinematic'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    audioFeatures: { energy: 0.32, valence: 0.48, danceability: 0.2, tempo: 80, acousticness: 0.65, instrumentalness: 0.7 },
    popularity: 85,
  },
  {
    title: 'Roja Theme',
    artist: 'A.R. Rahman',
    genre: 'Indian Classical',
    genres: ['Indian Classical', 'Focus', 'Cinematic'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    audioFeatures: { energy: 0.28, valence: 0.52, danceability: 0.18, tempo: 76, acousticness: 0.72, instrumentalness: 0.75 },
    popularity: 87,
  },
  {
    title: 'Breathless',
    artist: 'Shankar Mahadevan',
    genre: 'Fusion',
    genres: ['Fusion', 'Focus', 'Vocal'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    audioFeatures: { energy: 0.4, valence: 0.5, danceability: 0.25, tempo: 88, acousticness: 0.5, instrumentalness: 0 },
    popularity: 86,
  },
  {
    title: 'Raag Yaman Evening',
    artist: 'Pandit Ravi Shankar',
    genre: 'Indian Classical',
    genres: ['Indian Classical', 'Focus', 'Sitar'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    audioFeatures: { energy: 0.2, valence: 0.5, danceability: 0.1, tempo: 70, acousticness: 0.92, instrumentalness: 0.95 },
    popularity: 80,
  },
  {
    title: 'Tabla Solo Meditation',
    artist: 'Zakir Hussain',
    genre: 'Indian Classical',
    genres: ['Indian Classical', 'Focus', 'Tabla'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    audioFeatures: { energy: 0.35, valence: 0.5, danceability: 0.2, tempo: 85, acousticness: 0.85, instrumentalness: 0.9 },
    popularity: 78,
  },
  {
    title: 'Sadda Haq',
    artist: 'Mohit Chauhan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Focus', 'Alternative'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    audioFeatures: { energy: 0.4, valence: 0.48, danceability: 0.3, tempo: 90, acousticness: 0.45, instrumentalness: 0 },
    popularity: 84,
  },
  {
    title: 'Dil Chahta Hai',
    artist: 'Shankar Mahadevan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Focus', 'Feel-Good'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    audioFeatures: { energy: 0.38, valence: 0.55, danceability: 0.35, tempo: 88, acousticness: 0.4, instrumentalness: 0 },
    popularity: 91,
  },
  {
    title: 'Rang De Basanti',
    artist: 'A.R. Rahman',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Focus', 'Patriotic'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    audioFeatures: { energy: 0.42, valence: 0.5, danceability: 0.3, tempo: 90, acousticness: 0.5, instrumentalness: 0.1 },
    popularity: 89,
  },
  {
    title: 'Swades Theme',
    artist: 'A.R. Rahman',
    genre: 'Indian Classical',
    genres: ['Indian Classical', 'Focus', 'Cinematic'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    audioFeatures: { energy: 0.3, valence: 0.52, danceability: 0.2, tempo: 78, acousticness: 0.7, instrumentalness: 0.6 },
    popularity: 87,
  },
  {
    title: 'Kehna Hi Kya',
    artist: 'A.R. Rahman',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Focus', 'Soulful'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    audioFeatures: { energy: 0.25, valence: 0.5, danceability: 0.18, tempo: 75, acousticness: 0.72, instrumentalness: 0.2 },
    popularity: 83,
  },
  {
    title: 'Meethi Boliyaan',
    artist: 'Shankar Mahadevan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Focus', 'Uplifting'],
    mood: 'focus',
    image: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    audioFeatures: { energy: 0.35, valence: 0.52, danceability: 0.28, tempo: 82, acousticness: 0.55, instrumentalness: 0 },
    popularity: 81,
  },

  // ════════════════════════════════════════════
  //  ⚡ HYPER SONGS (14 songs)
  // ════════════════════════════════════════════
  {
    title: 'Lungi Dance',
    artist: 'Honey Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Hyper', 'Party'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1571266028243-d220c6a8b0e5?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
    audioFeatures: { energy: 0.95, valence: 0.85, danceability: 0.92, tempo: 150, acousticness: 0.02, instrumentalness: 0.1 },
    popularity: 95,
  },
  {
    title: 'DJ Wale Babu',
    artist: 'Badshah',
    genre: 'Hip-Hop',
    genres: ['Hip-Hop', 'Hyper', 'Party'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
    audioFeatures: { energy: 0.92, valence: 0.82, danceability: 0.9, tempo: 145, acousticness: 0.02, instrumentalness: 0.1 },
    popularity: 93,
  },
  {
    title: 'Gur Nalo Ishq Mitha',
    artist: 'Honey Singh',
    genre: 'Punjabi',
    genres: ['Punjabi', 'Hyper', 'Bhangra'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
    audioFeatures: { energy: 0.93, valence: 0.8, danceability: 0.88, tempo: 148, acousticness: 0.05, instrumentalness: 0.1 },
    popularity: 90,
  },
  {
    title: 'Paagal',
    artist: 'Badshah',
    genre: 'Hip-Hop',
    genres: ['Hip-Hop', 'Hyper', 'Rap'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
    audioFeatures: { energy: 0.95, valence: 0.78, danceability: 0.88, tempo: 152, acousticness: 0.02, instrumentalness: 0.15 },
    popularity: 88,
  },
  {
    title: 'Bom Diggy Diggy',
    artist: 'Zack Knight',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Hyper', 'Dance'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.9, valence: 0.82, danceability: 0.9, tempo: 140, acousticness: 0.05, instrumentalness: 0.1 },
    popularity: 91,
  },
  {
    title: 'Kala Chashma',
    artist: 'Neha Kakkar',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Hyper', 'Party'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.93, valence: 0.85, danceability: 0.92, tempo: 148, acousticness: 0.03, instrumentalness: 0.05 },
    popularity: 94,
  },
  {
    title: 'Desi Boyz',
    artist: 'Mika Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Hyper', 'Dance'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
    audioFeatures: { energy: 0.88, valence: 0.8, danceability: 0.85, tempo: 138, acousticness: 0.05, instrumentalness: 0.05 },
    popularity: 86,
  },
  {
    title: 'Garmi',
    artist: 'Badshah',
    genre: 'Hip-Hop',
    genres: ['Hip-Hop', 'Hyper', 'Dance'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
    audioFeatures: { energy: 0.92, valence: 0.78, danceability: 0.9, tempo: 145, acousticness: 0.02, instrumentalness: 0.1 },
    popularity: 89,
  },
  {
    title: 'Naach Meri Rani',
    artist: 'Guru Randhawa',
    genre: 'Punjabi',
    genres: ['Punjabi', 'Hyper', 'Dance'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
    audioFeatures: { energy: 0.9, valence: 0.82, danceability: 0.88, tempo: 142, acousticness: 0.05, instrumentalness: 0.1 },
    popularity: 90,
  },
  {
    title: 'Buzz',
    artist: 'Badshah',
    genre: 'Hip-Hop',
    genres: ['Hip-Hop', 'Hyper', 'Party'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
    audioFeatures: { energy: 0.88, valence: 0.8, danceability: 0.85, tempo: 140, acousticness: 0.05, instrumentalness: 0.1 },
    popularity: 87,
  },
  {
    title: 'Swag Se Swagat',
    artist: 'Vishal Dadlani',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Hyper', 'Anthem'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1517430529647-90cce5b4fb15?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    audioFeatures: { energy: 0.92, valence: 0.85, danceability: 0.88, tempo: 145, acousticness: 0.05, instrumentalness: 0.05 },
    popularity: 92,
  },
  {
    title: 'Chittiyaan Kalaiyaan',
    artist: 'Mika Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Hyper', 'Wedding'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
    audioFeatures: { energy: 0.88, valence: 0.82, danceability: 0.85, tempo: 140, acousticness: 0.05, instrumentalness: 0.05 },
    popularity: 88,
  },
  {
    title: 'Baby Doll',
    artist: 'Neha Kakkar',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Hyper', 'Item'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
    audioFeatures: { energy: 0.9, valence: 0.78, danceability: 0.88, tempo: 142, acousticness: 0.03, instrumentalness: 0.1 },
    popularity: 91,
  },
  {
    title: 'Nashe Si Chadh Gayi',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Hyper', 'Dance'],
    mood: 'hyper',
    image: 'https://images.unsplash.com/photo-1431440869543-efaf3388c585?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
    audioFeatures: { energy: 0.85, valence: 0.8, danceability: 0.82, tempo: 135, acousticness: 0.08, instrumentalness: 0 },
    popularity: 93,
  },

  // ════════════════════════════════════════════
  //  🌊 CHILLED SONGS (14 songs)
  // ════════════════════════════════════════════
  {
    title: 'Ilahi',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Chilled', 'Travel'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    audioFeatures: { energy: 0.35, valence: 0.6, danceability: 0.4, tempo: 95, acousticness: 0.5, instrumentalness: 0 },
    popularity: 90,
  },
  {
    title: 'Matargashti',
    artist: 'Mohit Chauhan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Chilled', 'Carefree'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    audioFeatures: { energy: 0.38, valence: 0.58, danceability: 0.42, tempo: 98, acousticness: 0.45, instrumentalness: 0 },
    popularity: 87,
  },
  {
    title: 'Dil Dhadakne Do',
    artist: 'Shankar Mahadevan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Chilled', 'Breezy'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    audioFeatures: { energy: 0.4, valence: 0.6, danceability: 0.45, tempo: 100, acousticness: 0.4, instrumentalness: 0 },
    popularity: 85,
  },
  {
    title: 'Safar',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Chilled', 'Journey'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1517430529647-90cce5b4fb15?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    audioFeatures: { energy: 0.32, valence: 0.55, danceability: 0.35, tempo: 90, acousticness: 0.55, instrumentalness: 0 },
    popularity: 88,
  },
  {
    title: 'Tera Yaar Hoon Main',
    artist: 'Arijit Singh',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Chilled', 'Friendship'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    audioFeatures: { energy: 0.35, valence: 0.6, danceability: 0.38, tempo: 92, acousticness: 0.5, instrumentalness: 0 },
    popularity: 86,
  },
  {
    title: 'Manja',
    artist: 'Amit Trivedi',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Chilled', 'Indie'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    audioFeatures: { energy: 0.3, valence: 0.55, danceability: 0.35, tempo: 88, acousticness: 0.55, instrumentalness: 0 },
    popularity: 82,
  },
  {
    title: 'Yeh Dooriyaan',
    artist: 'Mohit Chauhan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Chilled', 'Acoustic'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    audioFeatures: { energy: 0.28, valence: 0.52, danceability: 0.3, tempo: 85, acousticness: 0.6, instrumentalness: 0 },
    popularity: 84,
  },
  {
    title: 'Dil Ko Tumse Pyar Hua',
    artist: 'Kumar Sanu',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Classic', 'Chilled'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1446057032654-9d8885f0e7d7?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    audioFeatures: { energy: 0.3, valence: 0.58, danceability: 0.35, tempo: 88, acousticness: 0.58, instrumentalness: 0 },
    popularity: 83,
  },
  {
    title: 'Tum Ho Toh',
    artist: 'Mohit Chauhan',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Chilled', 'Breezy'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1528722828814-77b9b83aafb2?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    audioFeatures: { energy: 0.35, valence: 0.58, danceability: 0.4, tempo: 92, acousticness: 0.5, instrumentalness: 0 },
    popularity: 85,
  },
  {
    title: 'Kho Gaye Hum Kahan',
    artist: 'Jasleen Royal',
    genre: 'Indie',
    genres: ['Indie', 'Chilled', 'Dreamy'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    audioFeatures: { energy: 0.3, valence: 0.55, danceability: 0.35, tempo: 88, acousticness: 0.55, instrumentalness: 0 },
    popularity: 87,
  },
  {
    title: 'Pareshaan',
    artist: 'Amit Trivedi',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Chilled', 'Fun'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    audioFeatures: { energy: 0.38, valence: 0.6, danceability: 0.42, tempo: 95, acousticness: 0.45, instrumentalness: 0 },
    popularity: 84,
  },
  {
    title: 'Tum Jo Mil Gaye Ho',
    artist: 'Rafi',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Classic', 'Chilled'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    audioFeatures: { energy: 0.25, valence: 0.6, danceability: 0.3, tempo: 82, acousticness: 0.7, instrumentalness: 0 },
    popularity: 82,
  },
  {
    title: 'Haan Tu Hain',
    artist: 'KK',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Chilled', 'Love'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    audioFeatures: { energy: 0.32, valence: 0.58, danceability: 0.38, tempo: 90, acousticness: 0.52, instrumentalness: 0 },
    popularity: 85,
  },
  {
    title: 'Gulaabi Aankhen',
    artist: 'Kishore Kumar',
    genre: 'Bollywood',
    genres: ['Bollywood', 'Retro', 'Chilled'],
    mood: 'chilled',
    image: 'https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=500&h=500&fit=crop',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    audioFeatures: { energy: 0.35, valence: 0.65, danceability: 0.4, tempo: 92, acousticness: 0.5, instrumentalness: 0 },
    popularity: 90,
  },
];

// =============================================
//  SEED FUNCTION
// =============================================

const seedDatabase = async () => {
  try {
    console.log('🌱 Starting database seed — Indian Singers Edition...\n');
    
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB\n');

    // Clear existing data
    const existingCount = await Song.countDocuments();
    if (existingCount > 0) {
      console.log(`⚠️  Found ${existingCount} existing songs. Clearing...`);
      await Song.deleteMany({});
      console.log('🗑️  Existing songs cleared\n');
    }

    // Insert Indian singer songs
    const result = await Song.insertMany(dummySongs);
    console.log(`✅ Successfully inserted ${result.length} Indian singer songs!\n`);

    // Print summary by mood
    const moodCounts = {};
    for (const song of result) {
      moodCounts[song.mood] = (moodCounts[song.mood] || 0) + 1;
    }

    console.log('📊 Songs by mood:');
    console.log('─'.repeat(30));
    for (const [mood, count] of Object.entries(moodCounts).sort()) {
      console.log(`  ${mood.padEnd(12)} → ${count} songs`);
    }
    console.log('─'.repeat(30));
    console.log(`  Total        → ${result.length} songs\n`);

    // Print artist summary
    const artistCounts = {};
    for (const song of result) {
      artistCounts[song.artist] = (artistCounts[song.artist] || 0) + 1;
    }

    console.log('🎤 Songs by artist (top 15):');
    console.log('─'.repeat(40));
    const sortedArtists = Object.entries(artistCounts).sort((a, b) => b[1] - a[1]).slice(0, 15);
    for (const [artist, count] of sortedArtists) {
      console.log(`  ${artist.padEnd(25)} → ${count} songs`);
    }
    console.log('─'.repeat(40));

    console.log('\n🎉 Database seeded successfully with Indian singers!');
    console.log('🚀 Run "npm run dev" to start the server\n');

  } catch (error) {
    console.error('❌ Seed failed:', error.message);
  } finally {
    await mongoose.disconnect();
    console.log('📡 Disconnected from MongoDB');
    process.exit(0);
  }
};

// Run the seed
seedDatabase();
